








using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 2018-03-02 01:06:19Z
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CyrillicConverter.Translit.Implementation
{
	partial struct CyrillicToLatinConverter
	{
		private static readonly Dictionary<char, string>[] Rules =
		{

			new Dictionary<char, string> // 
			{

			},

			new Dictionary<char, string> // ru-RU
			{

			},

			new Dictionary<char, string> // be-BY
			{

			},

			new Dictionary<char, string> // uk-UA
			{

			},

			new Dictionary<char, string> // bg-BG
			{

			},

			new Dictionary<char, string> // mk-MK
			{

			},

		};
	}
}
