









// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 2018-03-02 01:05:56Z
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CyrillicConverter.Translit.Implementation
{
	partial struct LatinToCyrillicConverter
	{
		private struct ConvertRule
		{
			public readonly string Latin;
			public readonly string Cyrillic;

			public ConvertRule(string cyrillic, string latin)
			{
				Cyrillic = cyrillic;
				Latin = latin;				
			}
		}

		private static readonly ConvertRule[][] Rules = new []
		{

			new [] // 
			{

			},

			new [] // ru-RU
			{

			},

			new [] // be-BY
			{

			},

			new [] // uk-UA
			{

			},

			new [] // bg-BG
			{

			},

			new [] // mk-MK
			{

			},

		
		};
	}
}
